
services:
  web:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles  # <-- AquÃ­ se monta la carpeta generada por collectstatic

  db:
    image: postgres:15
    container_name: emmi_db_v2
    volumes:
      - postgres_emmi_data:/var/lib/postgresql/data/
    networks:
      - default
    restart: always
    environment:
      POSTGRES_DB: emmi_db
      POSTGRES_USER: ebyted
      POSTGRES_PASSWORD: arkano

volumes:
  postgres_emmi_data: 